[versions]
agp = "8.2.0" # "8.1.0" # "7.4.0"
lifecycle = "2.6.2" # "2.4.0"
compile-sdk = "34"

[libraries]
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }
