[versions]
coil = "3.0.0-alpha06"

[libraries]
compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil"}
network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil"}
