[versions]
okio = "3.6.0" # "3.3.0"

[libraries]
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fake = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
